import type { COE33ItemType } from '@/games/coe33/items/types';

export const weaponItems: COE33ItemType[] = [
  {
    name: 'Abysseram',
    description: '',
    internalSlug: 'Abysseram',
    slug: 'qkah',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Abyseram.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Algueron',
    description: '',
    internalSlug: 'Algueron',
    slug: 'm2su',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Algueron.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Angerim',
    description: '',
    internalSlug: 'Angerim',
    slug: '98eq',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Angerim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Ballaro',
    description: '',
    internalSlug: 'Sirenaro_1',
    slug: 'puin',
    imageUrl: 'weapons/T_UI_Monoco_Weapon_Sirenaro_1.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MONOCO',
  },
  {
    name: 'Barrier Breaker',
    description: '',
    internalSlug: 'Chainebum',
    slug: 'qwf5',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_BarrierBreaker.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Battlum',
    description: '',
    internalSlug: 'Battlum',
    slug: 'tlee',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Battlum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Benisim',
    description: '',
    internalSlug: 'Benisim',
    slug: '3ltl',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Benesim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Beselbum',
    description: '',
    internalSlug: 'Beselbum',
    slug: '8lax',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Default.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Betelim',
    description: '',
    internalSlug: 'Betelim',
    slug: '2zz8',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Betelim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Blizzon',
    description: '',
    internalSlug: 'Blizzon',
    slug: 'nqg5',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Blizzon.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Blodam',
    description: '',
    internalSlug: 'Blodam',
    slug: 'ibz4',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Blodam.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Boucharo',
    description: '',
    internalSlug: 'Boucharo',
    slug: 'd4gl',
    imageUrl: 'weapons/T_UI_Monoco_Weapon_Chapero.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MONOCO',
  },
  {
    name: 'Bourgelon',
    description: '',
    internalSlug: 'Bourgelon',
    slug: 'ok7z',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Bourgelon.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Braselim',
    description: '',
    internalSlug: 'Braselim',
    slug: 'q6oy',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Braselim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Brulerum',
    description: '',
    internalSlug: 'Brulerum',
    slug: 'a948',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Brulerum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Brumaro',
    description: '',
    internalSlug: 'Brumaro',
    slug: 'u287',
    imageUrl: 'weapons/T_UI_Monoco_Weapon_Brumaro.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MONOCO',
  },
  {
    name: 'Chalium',
    description: '',
    internalSlug: 'Chaliso',
    slug: 'gog1',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Dualim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Chantenum',
    description: '',
    internalSlug: 'Sirenum_2',
    slug: 'u7oa',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Sirenum_2.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Chapelim',
    description: '',
    internalSlug: 'Chapelim',
    slug: 'fh3v',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Boucharim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Charnon',
    description: '',
    internalSlug: 'Charnon',
    slug: 'l9tz',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Charnon.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Chation',
    description: '',
    internalSlug: 'Chation',
    slug: 'y56h',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Chation.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Chevalam',
    description: '',
    internalSlug: 'Chevalam',
    slug: '11r3',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Chevalam.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Choralim',
    description: '',
    internalSlug: 'Sirenim_1',
    slug: 's0ke',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Sirenim_1.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Chromaro',
    description: '',
    internalSlug: 'Chromaro',
    slug: 'dt7e',
    imageUrl: 'weapons/T_UI_Monoco_Weapon_Chromaro.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MONOCO',
  },
  {
    name: 'Clierum',
    description: '',
    internalSlug: 'Clierum',
    slug: 'i4ux',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Clierum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Coldum',
    description: '',
    internalSlug: 'Coldum',
    slug: 'qvxe',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Coldum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Colim',
    description: '',
    internalSlug: 'Sirenim_2',
    slug: '6pfd',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Sirenim_2.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Confuso',
    description: '',
    internalSlug: 'Confuso',
    slug: 'yj08',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Confuso.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Contorso',
    description: '',
    internalSlug: 'Moissoso',
    slug: 'suvz',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Contorson.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Coralim',
    description: '',
    internalSlug: 'Coralim',
    slug: 'ogso',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Coralim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Corderon',
    description: '',
    internalSlug: 'Corderon',
    slug: 'x3wl',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Corderon.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Corpeso',
    description: '',
    internalSlug: 'Corpeso',
    slug: 'h5mu',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Corpeso.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Cruleram',
    description: '',
    internalSlug: 'Cruleram',
    slug: 'pqvr',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Crueleram.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Cultam',
    description: '',
    internalSlug: 'Cultam',
    slug: 'oh6o',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Cultam.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Danseso',
    description: '',
    internalSlug: 'Danseso',
    slug: 'a59a',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Danseso.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Delaram',
    description: '',
    internalSlug: 'Delaram',
    slug: '93zh',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Delaram.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Deminerim',
    description: '',
    internalSlug: 'Deminerim',
    slug: 'yhoa',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Deminerim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Demonam',
    description: '',
    internalSlug: 'Demonam',
    slug: '0kl9',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Demonam.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Direton',
    description: '',
    internalSlug: 'Direton',
    slug: 'x9w8',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Direton.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Dreameso',
    description: '',
    internalSlug: 'Sireso_2',
    slug: '7ch9',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Sireso_2.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Dualiso',
    description: '',
    internalSlug: 'Dualim',
    slug: '3635',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Troubadim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Duenum',
    description: '',
    internalSlug: 'Duenum',
    slug: 'c95q',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Duenum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Elerim',
    description: '',
    internalSlug: 'Elerim',
    slug: '10l3',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Elerim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Facesum',
    description: '',
    internalSlug: 'Facesum',
    slug: 'grng',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Facesum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Fragaro',
    description: '',
    internalSlug: 'Reacharo_2',
    slug: '4eey',
    imageUrl: 'weapons/T_UI_Monoco_Weapon_Reacharo_2.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MONOCO',
  },
  {
    name: 'Garganon',
    description: '',
    internalSlug: 'Garganon',
    slug: '2rn3',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Garganon.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Gaulteram',
    description: '',
    internalSlug: 'Gaulteram',
    slug: '4qsd',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Gaulteram.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Gelerim',
    description: '',
    internalSlug: 'Gelerim',
    slug: 'v76l',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Default.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Gesam',
    description: '',
    internalSlug: 'Gesam',
    slug: 'cm7y',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Gesam.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Glaceso',
    description: '',
    internalSlug: 'Glaceso',
    slug: 'tedv',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Glaceso.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Glaisum',
    description: '',
    internalSlug: 'Glaisum',
    slug: '70kh',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Glaisum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Gobluson',
    description: '',
    internalSlug: 'Gobluson',
    slug: 'ex18',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Gobluson.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Grandaro',
    description: '',
    internalSlug: 'Grandaro',
    slug: 'jxu1',
    imageUrl: 'weapons/T_UI_Monoco_Weapon_Grandaro.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MONOCO',
  },
  {
    name: 'Guleson',
    description: '',
    internalSlug: 'Reacheron_1',
    slug: 'jmxk',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Reacheron_1.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Hevason',
    description: '',
    internalSlug: 'Hevason',
    slug: 'rc32',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Hevasson.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Jarum',
    description: '',
    internalSlug: 'Jarum',
    slug: 'w32o',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Jarum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Joyaro',
    description: '',
    internalSlug: 'Joyaro',
    slug: 'qdaf',
    imageUrl: 'weapons/T_UI_Monoco_Weapon_Joyaro.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MONOCO',
  },
  {
    name: 'Kralim',
    description: '',
    internalSlug: 'Reacherim_1',
    slug: 'zbn6',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Reacherim_2.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Lanceram',
    description: '',
    internalSlug: 'Lanceram',
    slug: 'r50j',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Lanceram.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Lighterim',
    description: '',
    internalSlug: 'Lighterim',
    slug: '4br5',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Lighterim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Liteso',
    description: '',
    internalSlug: 'Reacheso_2',
    slug: 'q2em',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Reacheaso.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Lithelim',
    description: '',
    internalSlug: 'Reacherim_2',
    slug: 'swcp',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Reacherim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Litheson',
    description: '',
    internalSlug: 'Reacheron_2',
    slug: 'vj34',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Reacheanon_2.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Lithum',
    description: '',
    internalSlug: 'Reachum_1',
    slug: 'nx3n',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Reachum_1.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Lunerim',
    description: '',
    internalSlug: 'Lunerim',
    slug: '5hyx',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Default.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Lusteson',
    description: '',
    internalSlug: 'Lusteson',
    slug: 'vyfu',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Lusteson.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Maellum',
    description: '',
    internalSlug: 'Maellum',
    slug: 'clhp',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Default.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Martenon',
    description: '',
    internalSlug: 'Sirenon_2',
    slug: '1xnz',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Sirenon_2.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Medalum',
    description: '',
    internalSlug: 'Medalum',
    slug: '4e4o',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Medalum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Melarum',
    description: '',
    internalSlug: 'Melarum',
    slug: 'ueci',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Melarum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Milerim',
    description: '',
    internalSlug: 'Milerim',
    slug: 'p7dn',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Default.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Minason',
    description: '',
    internalSlug: 'Minason',
    slug: 'd9kh',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Minason.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Moisson',
    description: '',
    internalSlug: 'Contorson',
    slug: 'eoxu',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Moissoson.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Monocaro',
    description: '',
    internalSlug: 'Monocaro',
    slug: 'n06i',
    imageUrl: 'weapons/T_UI_Monoco_Weapon_Default.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MONOCO',
  },
  {
    name: 'Nibalum',
    description: '',
    internalSlug: 'Nibalum',
    slug: 'jyio',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Default.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Noahram',
    description: '',
    internalSlug: 'Noahram',
    slug: 'io1r',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Default.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Nosaram',
    description: '',
    internalSlug: 'Nosaram',
    slug: 'oiwx',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Nosaram.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Nusaro',
    description: '',
    internalSlug: 'Reacharo_1',
    slug: 'k7pr',
    imageUrl: 'weapons/T_UI_Monoco_Weapon_Reachearo_1.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MONOCO',
  },
  {
    name: 'Painerim',
    description: '',
    internalSlug: 'Painerim',
    slug: 'yy0o',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Painerim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Plenum',
    description: '',
    internalSlug: 'Reachum_2',
    slug: '5q7x',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Reachum_2.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Potierim',
    description: '',
    internalSlug: 'Potierim',
    slug: 'xcx9',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Potierim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Ramasson',
    description: '',
    internalSlug: 'Ramasson',
    slug: 'khpn',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Ramasson.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Rangeson',
    description: '',
    internalSlug: 'Rangeson',
    slug: 'q5lf',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Rangeson.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Redalim',
    description: '',
    internalSlug: 'Redalim',
    slug: 'fyqw',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Redalim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Sadon',
    description: '',
    internalSlug: 'Sadon',
    slug: 'cian',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Sadon.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Sakaram',
    description: '',
    internalSlug: 'Sakaram',
    slug: 'f3zi',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Sakaram.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Saperim',
    description: '',
    internalSlug: 'Saperim',
    slug: '3smq',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Saperim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Scaverim',
    description: '',
    internalSlug: 'Scaverim',
    slug: 'ymdu',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Scaverim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Scieleson',
    description: '',
    internalSlug: 'Scieleson',
    slug: 'l1m7',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Default.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Seashelum',
    description: '',
    internalSlug: 'Seashelum',
    slug: '5h8c',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Seashellum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Seeram',
    description: '',
    internalSlug: 'Seeram',
    slug: 'uw6i',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Seeram.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Sekarum',
    description: '',
    internalSlug: 'Sekarum',
    slug: 'km5a',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Sekarum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Sidaro',
    description: '',
    internalSlug: 'Sidaro',
    slug: '7k1v',
    imageUrl: 'weapons/T_UI_Monoco_Weapon_Sidaro.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MONOCO',
  },
  {
    name: 'Simoso',
    description: '',
    internalSlug: 'Simoso',
    slug: '27lk',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Simoso.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Sireso',
    description: '',
    internalSlug: 'Sireso_1',
    slug: '6cse',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Sireso_1.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Snowim',
    description: '',
    internalSlug: 'Snowim',
    slug: 'qs8h',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Snowim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Stalum',
    description: '',
    internalSlug: 'Stalum',
    slug: 'o869',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Stallum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Telarim',
    description: '',
    internalSlug: 'Telarim',
    slug: 'lqft',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Default.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Tireso',
    description: '',
    internalSlug: 'Reacheso_1',
    slug: 'c7u7',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Reacheaso_1.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Tissenum',
    description: '',
    internalSlug: 'Sirenum_1',
    slug: 'vgoz',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Sirenum_1.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Tisseron',
    description: '',
    internalSlug: 'Sirenon_1',
    slug: 'keqo',
    imageUrl: 'weapons/T_UI_Sciel_Weapon_Sirenon_1.webp',
    category: 'WEAPON',
    tags: [],
    character: 'SCIEL',
  },
  {
    name: 'Trebuchim',
    description: '',
    internalSlug: 'Trebuchim',
    slug: 'ht9y',
    imageUrl: 'weapons/T_UI_Lune_Weapon_Trebuchim.webp',
    category: 'WEAPON',
    tags: [],
    character: 'LUNE',
  },
  {
    name: 'Troubadim',
    description: '',
    internalSlug: 'Troubadum',
    slug: 'rnrd',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Chalisum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Urnaro',
    description: '',
    internalSlug: 'Sirenaro_2',
    slug: 'eokw',
    imageUrl: 'weapons/T_UI_Monoco_Weapon_Sirenaro_2.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MONOCO',
  },
  {
    name: 'Velokan',
    description: '',
    internalSlug: 'Velokan',
    slug: 'y58s',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Default.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Veremum',
    description: '',
    internalSlug: 'Veremum',
    slug: '1vja',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Veremum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Verleso',
    description: '',
    internalSlug: 'Verleso',
    slug: '3upk',
    imageUrl: 'weapons/T_UI_Verso_Weapon_Default.webp',
    category: 'WEAPON',
    tags: [],
    character: 'VERSO',
  },
  {
    name: 'Volesterum',
    description: '',
    internalSlug: 'Volesterum',
    slug: '0ojy',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Volesterum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
  {
    name: 'Yeverum',
    description: '',
    internalSlug: 'Yeverum',
    slug: 'gbev',
    imageUrl: 'weapons/T_UI_Maelle_Weapon_Chainebum.webp',
    category: 'WEAPON',
    tags: [],
    character: 'MAELLE',
  },
];
